# Generated by Django 5.1.4 on 2024-12-31 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_food_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='discounted_price',
        ),
    ]
